### ISSUE TITLE
Agregar fecha y hora a las notas

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#14]
Cuando creamos una nota para la cuenta de los clientes es necesario agregar
la fecha y la hora en la que se agrego dicha nota.

**Comment by alfonsonv** [comment]
Se agregó la columna hora a la tabla notas:
ALTER TABLE notas ADD COLUMN `hora` TIME NULL AFTER `fecha`;
Se cambió la hora de estilo para cambiar el formato de nota acorde para mostrar más información.

**Comment by alfonsonv** [comment]
No me dijiste que ya habías cambiado el campo fecha a datetime...

**Comment by alfonsonv** [comment]
Asunto arreglado.
