### ISSUE TITLE
 Eliminar notas:

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#15]
Agregar la funcionalidad solo para el "Administrador" para poder eliminar las notas de los clientes.
Se sugiere hacerlo por AJAX o js para no tener que refrescar la pagina.
Sera necesario un checkbox en cada nota para seleccionar las que desea eliminar.

**Comment by alfonsonv** [comment]
Pues ya con estos cambios ya queda funcionando con jquery

**Comment by juanmarin** [comment]
No funciona en produccion, al seleccionar las notas el boton no llama la funcion

**Comment by juanmarin** [comment]
El problema es el google chrome de Linux en firefox si funciona correctamente, se revisaran los navegadores con windows

**Comment by alfonsonv** [comment]
Que bueno que me dices, para buscarle por allí.

**Comment by juanmarin** [comment]
- Es necesario validar que la funcionalidad para eliminar notas este solo disponible para el usuario administrador.
- Si no hay notas no es necesario mostrar el boton

**Comment by alfonsonv** [comment]
Lo probé en firefox y chrome de linux y si funcionó.

**Comment by alfonsonv** [comment]
Ya probé en windows 7, ambos navegadores y también funciona bien.

**Comment by alfonsonv** [comment]
Favor de verificar, creo que con estos cambios ya queda listo lo de las notas.

**Comment by juanmarin** [comment]
Funciona correctamente
