### ISSUE TITLE
Restringir pagos

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#17]
Nueva funcionalidad respecto al manejo de pagos, ahora tendran que deshabilitarse todos los pagos menos los que esten vencidos y el mas prooximo a vencer, es decir; Si un cliente tiene 2 pagos vencidos y uno se vence el dia de mañana este solo tendra habilitados 3 pagos, una vez que estos esten cubiertos se deshabilitara el siguiente.

**Comment by alfonsonv** [comment]
Terminado, favor de comprobar y proveer retroalimentación para cerrar caso.

**Comment by juanmarin** [comment]
Correcto, cerramos issue
