### ISSUE TITLE
Pagos de recargos

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#18]
Ya que como la mayotia de losclientes NO paga los recargos por demoras en su totalidad, es necesario agregar un input text  en la parte de los recargos para poder agregar ya sea el total o el abono parcial de estos. 
Solo el administrador tendra la facultad de condonar los recargos.

**Comment by alfonsonv** [comment]
Debe quedar un solo cuadro de pago con el total?

**Comment by alfonsonv** [comment]
Debe ser obligatorio el pago/abono de recargos?

**Comment by juanmarin** [comment]
- Sera un input para cada recargo por pagar
- Los recargos no seran obligatorios pero solo el administrador puede condonarlos
- Los cobradores solo podran ingresar la cantidad recibida por cobro de recargos mediante el campo input. En caso de no liquidar el recargo en su totalidad el campo input seguira apareciendo con la cantidad restante para cubirl el pago total del recargo.

**Comment by alfonsonv** [comment]
Hola, favor de revisar el nuevo manejo de recargos.

**Comment by juanmarin** [comment]
Hizo falta la funcionalidad para condonar los recargos solo como administrador, pero al parecer el cliente no lo ha notado :smile:  
Asi que se cerrara en issue y en caso de ser necesario se agregara la funcionalidad
