### ISSUE TITLE
Agregar pagos decenales

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#21]
Es necesario agregar un nuevo tipo de pago, este sera cada 10 días contados aparir de la fecha del préstamo, es decir que si el préstamo se efectuó el 12-06-2015, el sistema empezara a contar 10 días a partir de esta fecha quedando como fecha del primer pago el día 22-06-15, 02-07-2015 ... etc.

**Comment by juanmarin** [comment]
No se hara este cambio

**Comment by alfonsonv** [comment]
Shh en eso estaba... Va.

**Comment by juanmarin** [comment]
:-1: Sorry

**Comment by alfonsonv** [comment]
No hay falla.
