### ISSUE TITLE
Prestamos quincenales y mensuales

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#22]
- Cuando se hace un préstamo con pagos tipo quincenal, la fecha de pago se repite en todos lospagos
  ![prestamos_quincenales](https://cloud.githubusercontent.com/assets/5942289/8323286/2773ec3a-19f7-11e5-8213-f000dbdd559f.png)
- Cuando se crea un prestamos tipo mensual no se abre la cuenta.

Esto ya se habia corregido en una version pero al parecer se sobreescribio el archivo por uno viejo

**Comment by alfonsonv** [comment]
No había tal error.

**Comment by juanmarin** [comment]
Yo lo pude reproducir, viste el usuario test test ?
Esto paso en  mi local y en producción
Checa la imagen
