### ISSUE TITLE
Mover recargos

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#25]
Los recargos deberán de ser movidos al área donde se encuentran los pagos para esto habrá que reducir los espacios, cambiar la fecha de pago a formato d-m-A, los recargos se colocaran al extremos derecho de la tabla cuenta.

**Comment by alfonsonv** [comment]
Que ondas ya lo moví pero no me gusta como quedan, no caben bien, tuve que quitar la fecha del recargo porque no cabían.
Chécalo en tu laptop, en una pc mas o menos caben pero con el ancho de la laptop no, mucho menos una tablet.

**Comment by juanmarin** [comment]
Estoy de acuerdo contigo, no me gusta y no se vera bien en un cel.

**Comment by juanmarin** [comment]
Se movio la informacion solicitada, se agregaran iconos en vez de botones
