### ISSUE TITLE
Agregar funcionalidad para cargar mas fotos al perfil del cliente ( IFE Adverso y Reverso)

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#38]
Agregar campos en la aplicacion y base de datos para capturar imagen de la credencial de elector de los clientes, esta sera almacenada en base de datos y podra ser mostrada en la cuenta del cliente

**Comment by alfonsonv** [comment]
Desde donde se agrega la imagen?, desde crear cliente, editar cliente o cuenta?

**Comment by juanmarin** [comment]
Sera necesario permitir agregar mas imagenes al perfil del cliente, favor de agregar icono para adjuntar imagenes correspondietes a avales, y domicilio del cliente.
Srian en total 6 Imagenes por cliente.
1 -> Perfil
2 -> INE
2-> Avales
2--> Domicilio del cliente
Ademas las imagenes deberan de poder ser agregadas desde 
1 -> Captura del cliente
2 -> Edicion de cliente
3 -> Desde la cuenta del cliente
