### ISSUE TITLE
PAGINA CLIENTES ACTIVOS

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#4]
notaq_s/?pg=2cb  DONDE DICE CARGO, QUE SALGA EL SALDO EN LUGAR DEL MONTO

**Comment by alfonsonv** [comment]
Resuelto. Para esto se modificaron 3 archivos: 
sys_panel.php
pg_cliente_cuenta.php
pg_clientes_activos.php

Quedo en espera de tu revisión para cerrar el issue.
