### ISSUE TITLE
AGREGAR FUNCIONALIDAD PARA CARGAR ARCHIVO DE IMAGEN

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#5]
El proceso para cargar archivos de imágenes del cliente ya no sera automático, sera de forma manual con un campo tipo upload.

**Comment by alfonsonv** [comment]
En qué sección se carga la imagen, durante la alta o en editar cliente?

**Comment by juanmarin** [comment]
Se cargara la imagen del cliente al crear la cuenta, como se hacia con el metodo anterior

**Comment by alfonsonv** [comment]
Se creó tabla para almacenar imagen tipo blob:
CREATE TABLE `clientefoto` (
  `idfoto` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `idcliente` int(11) NOT NULL,
  `foto` blob NOT NULL,
  PRIMARY KEY (`idfoto`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;

**Comment by alfonsonv** [comment]
Se actualizó formulario para insertar foto de cliente

**Comment by alfonsonv** [comment]
Ya se puede insertar imágenes JPG en cliente, en una tabla alterna para que el peso de la misma no afecte a las consultas de cliente.
Falta mostrar la imagen, donde será mostrada?

**Comment by juanmarin** [comment]
La imagen se mostrara en la pagina pg_cliente_cuenta.php

**Comment by alfonsonv** [comment]
Listo, solo falta poner una imagen para mostrar por defecto pero no he encontrado un icono de usuario de 200x200 luego lo agrego.

**Comment by juanmarin** [comment]
Se encontro esta imagen a ver si te sirve
![perfil_notaq_200x200](https://cloud.githubusercontent.com/assets/5942289/7849588/cd945b26-048b-11e5-9646-a50e04136178.png)

La misma en otro tamaño
![perfil_notaq](https://cloud.githubusercontent.com/assets/5942289/7849591/dc37bd76-048b-11e5-9f2d-23b8d06acf25.png)

Espero sirva y te agrade
