### ISSUE TITLE
SECCION DE REPORTES

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#7]
Seccion Reportes ?pg=3c
Al Reporte:
- Diario
- Por fechas
- Lista de cobranza
- Recargos
  Es necesario agregar un select que permita filtrar los resultados de las consultas por cobrador.

**Comment by alfonsonv** [comment]
Esos 4 reportes necesitan un select para filtrar por cobrador, eso entiendo, ¿si el usuario es un cobrador tiene acceso a esos reportes?, si es así entonces será necesario que solo pueda seleccionar a el mismo como cobrador, o en su defecto que no aparezca select y se filtre automáticamente por el usuario loguedo.

**Comment by juanmarin** [comment]
Solo el administrador podra ver este select, es el unico que puede ver lo de los demas

**Comment by alfonsonv** [comment]
Hola, issue resuelto, favor de validar y cerrarlo.
