### ISSUE TITLE
Restringir Clientes

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#8]
Actualmente existen 2 tipos de usuarios en el sistema.
1 .- ADMINISTRADOR: El cual puede ver toda la cartera y el listado de clientes.
2 .- COBRADOR: El cual debera de poder ver unicamente el listado de clientes y cuentas que estan asignados a el.

**Comment by juanmarin** [comment]
Se trabajo con el reporte diario, archivo
pg_reporte_diario.php
Ya se encuentra en github y el ftp

**Comment by juanmarin** [comment]
Se agregaron las restriciones a la seccion de 
- Mis clientes
- Mis clietes Activos
- Mis clientes Vencidos

**Comment by alfonsonv** [comment]
Está cerrado este issue? que le falta?

**Comment by juanmarin** [comment]
Se corrigio detalle en reporte diario habia un error con la validacion del usuario en session.
Se agrego htmlentities() en el action del post

**Comment by juanmarin** [comment]
Listo cambios aplicados en sitio confianzp

**Comment by juanmarin** [comment]
Tarea terminada.
