### ISSUE TITLE
Exportar consultas a Excel

### ISSUE THREAD

**Issue by juanmarin** [juanmarin/notaq_s#9]
Es necesario crear una seccion en el sistema la cual contendra los diferentes tipos de reportes exportables a excel.
Queda pendiente por definir el numero de consultas y la info que se obtendra de cada una de ellas

**Comment by alfonsonv** [comment]
¿Qué nivel podrá ver esa opción de generar reporte de excel?

**Comment by alfonsonv** [comment]
Solo administrador.

**Comment by juanmarin** [comment]
Solo el administrador podra tener acceso a este reporte

**Comment by alfonsonv** [comment]
Hola, issue resuelto. Solo faltaría agregar los reportes que necesitas.

**Comment by juanmarin** [comment]
Se agregaron a la consulta los campos Sector, referencias y numeros de las referencias,

**Comment by juanmarin** [comment]
Done
